---
clone:
  depth: 1
kind: pipeline
name: el9 amd64 build
pull: always
steps:
- commands:
  - aws ecr get-login-password --region us-east-2 | docker login --username AWS --password-stdin
    084037375216.dkr.ecr.us-east-2.amazonaws.com
  - ./ci/scripts/build.sh el9 amd64 100.0.0+${DRONE_COMMIT_SHA:0:8} ${DRONE_BUILD_EVENT}
  image: 084037375216.dkr.ecr.us-east-2.amazonaws.com/honda-builder
  name: build
- commands:
  - ls -la el9
  image: 084037375216.dkr.ecr.us-east-2.amazonaws.com/honda-builder
  name: list
trigger:
  event:
  - push
  - tag
  - custom
type: docker
---
clone:
  depth: 1
kind: pipeline
name: el9 arm64 build
platform:
  arch: arm64
  os: linux
pull: always
steps:
- commands:
  - aws ecr get-login-password --region us-east-2 | docker login --username AWS --password-stdin
    084037375216.dkr.ecr.us-east-2.amazonaws.com
  - ./ci/scripts/build.sh el9 arm64 100.0.0+${DRONE_COMMIT_SHA:0:8} ${DRONE_BUILD_EVENT}
  image: 084037375216.dkr.ecr.us-east-2.amazonaws.com/honda-builder
  name: build
- commands:
  - ls -la el9
  image: 084037375216.dkr.ecr.us-east-2.amazonaws.com/honda-builder
  name: list
trigger:
  event:
  - push
  - tag
  - custom
type: docker
